### ISSUE TITLE
Defaults without keywords if types are distinct?

### ISSUE THREAD

**Issue by ahwillia** [mauro3/Parameters.jl#15] opened 2016-09-08 06:21 UTC
Could the following be made to work?

``` julia
@any_order type A
    a::Int = 1
    b::Float64 = 5.0
end

A() # gives A(1,5.0)
A(3) # gives A(3,5.0)
A(1.2) # gives A(1,1.2)
```

I'd also like to do this for functions:

``` julia
@any_order function f(x::Int, y::Float64)
    ...
end
```

The macro then defines:

``` julia
f(y::Float64, x::Int) = f(x,y)
```

This stemmed from a chat on gitter with @oxinabox and @ScottPJones. This is implemented for certain functions in Base, e.g. `scale!`

**Comment by oxinabox** [comment] 2016-09-08 06:48
I don't see any reason for this to be in Base.
Unless there are enough functions in Base that use it, 
in which case it would be a way to make the code a bit cleaner maybe.

I can envision a package with a number of utililty macros from declaring function variants.

**Comment by mauro3** [comment] 2016-09-08 13:32
I don't think I like this feature, seems to me that it would be easy lead to bugs.  But I will ponder it for a bit and I'll let you know whether I'd accept a PR...

**Comment by damiendr** [comment] 2016-09-08 13:37
To chime in, I have a few examples in my code where I pass integer constants for float parameters, (just because it works, no particular reason other than brevity). I always use keywords though.

**Comment by damiendr** [comment] 2016-09-08 13:42
I have a feeling the expected behaviour isn't well defined if there is more than one field of each type, and depends on the semantics rather than on the structure of the args/fields.

**Comment by mauro3** [comment] 2016-09-08 14:30
Yes, I think this probably only makes sense for types with a few fields only, say:
```
@with_kw type Person
 name::String="John"
 age::Int=0
 height::Float64=1.7
end
```
Whereas for types with more fields it would be more and more error-prone.  And for types with a few fields those constructors are easy to write by hand.

**Comment by ahwillia** [comment] 2016-09-08 18:24
My use case is for functions like this:

```
fit_model(data::Array, distance::SemiMetric, options::MyFittingOptions, ... )
```

I actually don't really need the default values if that is what you are worried about. It could get tricky if you had parametric functions/types, but maybe we would not support that? I suppose it would also be ambiguous if certain arguments are subtypes:

```
f(x::Array, y::AbstractArray, ... )
```

Other than that, I'm not sure how this would lead to bugs/errors...

**Comment by mauro3** [comment] 2017-02-14 14:16
I'll close this as I don't think I want to support this feature.  Thanks @ahwillia for your feedback!

**Closed by mauro3** 2017-02-14 14:16 UTC
